### ISSUE TITLE
Suspense & Solid app router together will break the suspense fallback.

### ISSUE THREAD

**Issue by ivands** [solidjs/solid-app-router#60] opened 2021-12-12 10:55 UTC
Suspense & Solid app router together will break the suspense fallback if you click on a link where a resource is loading.
The page will be blocked instead until the resource is done loading.
I'm guessing this isn't expected behavior.

Example:
```
//App.js
export default () => {
  const Routes = useRoutes(routes);

  <Suspense fallback={<p>Loading Page...</p>}>
    <Routes />
  </Suspense>
};

//Dashboard.js
export default () => {
	const [data] = createResource(() => {
		return new Promise((resolve) => {
			setTimeout(() => {
				resolve('DATA LOADED');
			}, 3000);
		});
	});

	return <div>Dashboard Page {data()}</div>;
};
```

**Comment by ryansolid** [comment] 2021-12-13 06:21
This is intentional. There is a feature called [Transitions](https://www.solidjs.com/tutorial/async_transitions) that are baked into the router that do this hold mechanism and allow with the use of `isRouting` to indicate stale state. If you want to show fallback put the Suspense boundary below the route(in your page) is generally the recommended way.

For more information on the reasoning behind this these slightly outdated React docs might help(https://reactjs.org/docs/concurrent-mode-patterns.html#the-three-steps). Since the time of posting the timeout on transitions was removed the decision on when to show fallback is simply is it newly rendered. Once there is established main content the fallback doesn't show up.

**Comment by ivands** [comment] 2021-12-14 07:52
But wouldn't that mean that you would have to wrap every route inside a Suspense tag instead of having a single Suspense tag wrapping all the routes? Seems a little weird to me.

**Comment by ryansolid** [comment] 2022-02-17 06:22
Closing as by design. It's possible with the right proposal we can consider this but generally it is work as expected.

**Closed by ryansolid** 2022-02-17 06:22 UTC
