### ISSUE TITLE
please helpme error

### ISSUE THREAD

**Issue by radensoft** [solidjs/solid-app-router#80] opened 2022-02-03 08:28 UTC
file:///C:/Users/info/Downloads/vite-ssr-solid-master/node_modules/solid-app-router/dist/index.js:1
import { isServer, template, createComponent as createComponent$1, mergeProps, delegateEvents, spread, insert, effect, setAttribute } from 'solid-js/web';
                                                                                                               ^^^^^^
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'effect'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:120:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:165:5)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async nodeImport (C:\Users\info\Downloads\vite-ssr-solid-master\node_modules\vite\dist\node\chunks\dep-f5552faa.js:60169:21)
    at async eval (/src/routes.tsx:5:31)
    at async instantiateModule (C:\Users\info\Downloads\vite-ssr-solid-master\node_modules\vite\dist\node\chunks\dep-f5552faa.js:60105:9)

**Comment by ryansolid** [comment] 2022-02-17 06:19
This looks like a duplicate of #79. Closing.

**Closed by ryansolid** 2022-02-17 06:19 UTC
